name: ci

on:
  push:
    paths:
      - "**.ts"
      - "**.yml"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js to 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: yarn

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run ESLint
        run: yarn run eslint src/**/*.ts

      - name: Run TypeScript
        run: yarn run tsc --project tsconfig.json --noEmit
